apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: ubuntu1604-block-template
  namespace: default
spec:
  source:
    registry:
      url: "docker://camelcasenotation/ubuntu1604-containerdisk"
  pvc:
    storageClassName: $STORAGECLASS_NAME
    accessModes:
    - $ACCESS_MODES
    resources:
      requests:
        storage: $STORAGE_REQUEST_GREATER_THAN_1GB
